### ISSUE TITLE
The nums of images?

### ISSUE THREAD

**Issue by shipengai** [thunlp/Muffin#2]
The images that have all 5 types annotations only is 1304.
But I found the UniMM-Chat dataset is larger than 1304

**Comment by Haoye17** [comment]
Hello @shipengai! Thanks for your interest in our work and sorry for the delay! 

As for the image amount we used, each sample in our dataset has a different image, which means a total of 117,238 COCO images are included. 
In the process of data construction, we use as much annotation as possible for each image, so if there are less than 5 types of annotations for the image, we only use the 3 or 4 types of annotations it has as the given information to ChatGPT. Since every COCO image has captions, VQAv2, and Visual Dialog annotations, at least 3 types of information are included for each image, which is helpful for information fusion.

Hope this information is helpful to you~
